### PR TITLE
Added cafe music to base scene

### PR DESCRIPTION
**Pull request by drw0469**
Added music to the cafe.

### CODE REVIEW

**Comment by RayGar** [comment]
It works but we need the Audio Source to be set on 3D by default and we also want the song to loop (just check the box labeled "Loop" on the inspector.

**Review by RayGar — CHANGES_REQUESTED** [review]
It works but we need the Audio Source to be set on 3D by default and we also want the song to loop (just check the box labeled "Loop" on the inspector.

**Comment by RayGar** [comment]
The changes that I asked were made, but the volume it is at right now (3.5) is too low. Raise it to at least 7.5 and I'll approve your PR.

**Comment by zliving** [comment]
I don't agree with Ray, I think the music is too loud and it doesn't drop off soon enough. The ambient sound distance should be much shorter. I shouldn't hear it loud out in the street

**Comment by cvasqu09** [comment]
Merged David's branch into mine. No need to put this in develop anymore

**Pull request closed without merging**
